apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfc-agents
  namespace: tfc-agents
spec:
  replicas: 1
  selector:
    matchLabels: { app: tfc-agents }
  template:
    metadata:
      labels: { app: tfc-agents }
    spec:
      containers:
        - name: tfc-agents
          image: hashicorp/tfc-agents:1.23
          envFrom:
            - secretRef:
                name: tfc-agents-env
          resources: {}
