namespace: metallb-system

addressPool:
  name: pool
  protocol: layer2
  addresses: [] # e.g. ["192.168.3.250-192.168.3.250"]
  autoAssign: true
  avoidBuggyIPs: false

l2Advertisement:
  enabled: true
  name: l2
  interfaces:
    - '*'
