apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-cert
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames: ['argocd.apps.klab.internal']
  issuerRef: { kind: ClusterIssuer, name: homelab-ca }
