apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-egress
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-15' } # alongside cilium-lb
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/cilium-egress/overlays/klab
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
