apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netshoot
  namespace: debug
spec:
  selector:
    matchLabels: { app: netshoot }
  template:
    metadata:
      labels: { app: netshoot }
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      containers:
        - name: netshoot
          image: nicolaka/netshoot:latest
          command: ['bash', '-lc', 'sleep infinity']
          securityContext:
            privileged: true
      restartPolicy: Always
  updateStrategy: { type: RollingUpdate }
