apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-100'
spec:
  description: Platform building blocks (networking, ingress, PKI, exposures)
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/greg-court/homelab.git
    - https://charts.jetstack.io
    - https://metallb.github.io/metallb
    - https://charts.external-secrets.io
    - https://traefik.github.io/charts
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
