apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-5' }
spec:
  project: platform
  destination: { server: https://kubernetes.default.svc, namespace: monitoring }
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 76.2.0
    helm:
      values: |
        defaultRules:
          create: true

        kubeProxy:
          enabled: false  # you're on Cilium, so no kube-proxy

        kubeEtcd:
          enabled: false  # usually not reachable externally on bare-metal

        kubeControllerManager:
          enabled: false  # disable unless you expose it

        kubeScheduler:
          enabled: false  # disable unless you expose it

        prometheus:
          prometheusSpec:
            retention: 14d
            walCompression: true
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: prometheus-local
                  resources:
                    requests:
                      storage: 32Gi
        alertmanager:
          enabled: true
          alertmanagerSpec:
            storage: {}   # ephemeral (you said you don't care about history)
        grafana:
          enabled: true
          defaultDashboardsTimezone: browser
          service:
            type: ClusterIP
          persistence:
            enabled: false
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true # handles CRD race on first sync
