apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expose-hubble
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # Ingress must live with hubble-ui Service
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: charts/ingress-app
    helm:
      values: |
        host: hubble.trust.k8s.internal
        ingressClassName: nginx
        service:
          name: hubble-ui
          namespace: kube-system
          port: 80
        tls:
          enabled: true
          secretName: hubble-trust-tls
          clusterIssuer: homelab-ca
  syncPolicy:
    automated: { prune: true, selfHeal: true }
