apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agents-and-runners
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: agents-and-runners
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: apps/agents-and-runners
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
