apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  # Wave 0 so that any chart needing certificates (ESO, Istio, …) can be wave 1+
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true]
