apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-namespace
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-29' }
spec:
  project: platform
  destination: { server: https://kubernetes.default.svc, namespace: monitoring }
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/charts/namespace-privileged
    helm:
      values: |
        name: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
