apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-crds
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-11' }
spec:
  project: platform
  destination: { server: https://kubernetes.default.svc, namespace: traefik }
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik-crds
    targetRevision: 1.8.1
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ['CreateNamespace=true']
