apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.0
    helm:
      values: |
        controller:
          ingressClassResource:
            name: nginx
            default: true
          service:
            type: LoadBalancer
            annotations:
              metallb.io/address-pool: dmz-pool
              metallb.io/loadBalancerIPs: 192.168.4.250
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ['CreateNamespace=true']
