apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-favicons
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-favicons
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: apps/nginx-favicons
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ['CreateNamespace=true']
