image:
  repository: docker.io/gr10/gh-packer-runner
  tag: 1.0.0
  pullPolicy: IfNotPresent

count: 2 # how many runners
replicas: 1 # per runner

external:
  vip: 192.168.3.251 # dedicated VIP for packer
  shareKey: packer-251 # any string; same on all services
  basePort: 8081 # runner-1=8081, runner-2=8082, ...
  domain: packer.trust.k8s.internal
  addressPool: klab-pool

envFromSecrets: [] # e.g. ["gh-runners-env"]
envFromConfigMaps: [] # e.g. ["gh-runners-config"]

extraEnv:
  - name: RUNNER_LABELS
    value: 'self-hosted,packer'

podAnnotations: {}
resources:
  requests:
    cpu: '200m'
    memory: '256Mi'
  limits:
    cpu: '2'
    memory: '2Gi'
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []

podSecurityContext:
  fsGroup: 1000

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: ['ALL']
