plugin: community.proxmox.proxmox

validate_certs: false
want_facts: true

keyed_groups:
  - key: 'config.ostype'
    prefix: 'os'
  - key: 'tags'
    prefix: ''

groups:
  debian_based: >-
    (
      (proxmox_vmtype == 'lxc' and proxmox_ostype in ['ubuntu', 'debian'])
      or
      ('debian-based' in (proxmox_tags | default([])))
    )
    and ('no-ansible' not in (group_names | default([])))
  linux: >-
    ((proxmox_vmtype == 'lxc') or (proxmox_ostype == 'l26'))
    and ('no-ansible' not in (proxmox_tags | default([])))
  test: >-
    inventory_hostname in ['ITADM-UBU24']
  kubernetes_controller: inventory_hostname == 'K8S-CTRL'
  kubernetes_nodes: inventory_hostname in ['K8S-GREG', 'K8S-DMZ']
  kubernetes: >-
    inventory_hostname in ['K8S-CTRL', 'K8S-GREG', 'K8S-DMZ']

compose:
  ansible_host: 'agent_interfaces[0].ip_addresses[0].ip_address'
