apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-default-vlan3
spec:
  # Match pods that do NOT have an egress.zone label
  selectors:
    - podSelector:
        matchExpressions:
          - key: egress.zone
            operator: DoesNotExist
  destinationCIDRs: ['0.0.0.0/0', '::/0']
  egressGateway:
    interface: 'enp0s31f6.3'
