apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-fam-vlan6
spec:
  selectors:
    - podSelector:
        matchLabels:
          egress.zone: 'fam'
  destinationCIDRs: ['0.0.0.0/0', '::/0']
  egressGateway:
    nodeSelector: {}
    interface: 'enp0s31f6.6'
