defaultRules: { create: true }

kubeProxy: { enabled: false }
kubeEtcd: { enabled: false }
kubeControllerManager: { enabled: false }
kubeScheduler: { enabled: false }

prometheusOperator:
  admissionWebhooks:
    certManager:
      enabled: true
      issuerRef:
        { name: homelab-ca, kind: ClusterIssuer, group: cert-manager.io }
    createSecretJob: { enabled: false }
    patch: { enabled: false }

prometheus:
  prometheusSpec:
    retention: 14d
    retentionSize: '24GiB'
    walCompression: true
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-data
        spec:
          storageClassName: local-path
          resources:
            requests:
              storage: 32Gi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534 # 'nobody' in the prom image
      runAsGroup: 65534
      fsGroup: 65534
      fsGroupChangePolicy: Always

    initContainers:
      - name: fix-permissions
        image: busybox:1.36
        command:
          - sh
          - -euxc
          - |
            chown -R 65534:65534 /prometheus
            chmod -R g+rwX /prometheus
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        volumeMounts:
          - name: prometheus-data # must match the metadata.name above
            mountPath: /prometheus

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage: {}

grafana:
  enabled: true
  defaultDashboardsTimezone: browser
  persistence: { enabled: false }
  service: { type: ClusterIP }
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      isDefault: false
    - name: Alertmanager
      type: alertmanager
      uid: alertmanager
      access: proxy
      url: http://kube-prometheus-stack-alertmanager.monitoring.svc:9093
      jsonData: { implementation: prometheus }
  ingress:
    enabled: true
    ingressClassName: trust
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca
    # these are overridden per cluster
    hosts: []
    tls: []
