apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: agents-and-runners
  labels: { app: buildkitd }
spec:
  type: ClusterIP
  selector: { app: buildkitd }
  ports:
    - name: grpc
      port: 1234
      targetPort: grpc
