spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: gh-packer-runner
      instance: "{{ $suffix }}"
  template:
    metadata:
      labels:
        app: gh-packer-runner
        instance: "{{ $suffix }}"
{{- if $.Values.podAnnotations }}
      annotations: {{ toYaml $.Values.podAnnotations | nindent 8 | trim }}
{{- end }}
    spec:
{{- if $.Values.podSecurityContext }}
      securityContext:
{{ toYaml $.Values.podSecurityContext | nindent 8 }}
{{- end }}
      containers:
        - name: gh-packer-runner
          image: "{{ $image.repository }}:{{ $image.tag }}"
          imagePullPolicy: {{ $image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
          env:
            - name: EXTERNAL_HTTP_PORT
              value: "{{ add $basePort $i }}"
            - name: RUNNER_HOSTNAME
              value: "{{ $domain }}"
            - name: RUNNER_NAME
              value: "packer-runner-{{ $suffix }}"
{{- range $.Values.extraEnv }}
            - name: {{ .name }}
              value: "{{ .value }}"
{{- end }}
{{- if or $.Values.envFromSecrets $.Values.envFromConfigMaps }}
          envFrom:
{{- range $.Values.envFromSecrets }}
            - secretRef:
                name: {{ . }}
{{- end }}
{{- range $.Values.envFromConfigMaps }}
            - configMapRef:
                name: {{ . }}
{{- end }}
{{- end }}
{{- if $.Values.containerSecurityContext }}
          securityContext:
{{ toYaml $.Values.containerSecurityContext | nindent 12 }}
{{- end }}