{{- $count := int .Values.count -}}
{{- $basePort := int .Values.external.basePort -}}
{{- $vip := .Values.external.vip -}}
{{- $shareKey := .Values.external.shareKey -}}

{{- range $i, $_ := until $count }}
{{- if gt $i 0 }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: gh-packer-runner-{{ printf "%02d" (add $i 1) }}
  annotations:
    metallb.io/address-pool: {{ .Values.external.addressPool }}
    metallb.io/allow-shared-ip: {{ $shareKey | quote }}
  labels:
    app: gh-packer-runner
    instance: "{{ printf "%02d" (add $i 1) }}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: {{ $vip }}
  selector:
    app: gh-packer-runner
    instance: "{{ printf "%02d" (add $i 1) }}"
  ports:
    - name: http
      port: {{ add $basePort $i }}
      targetPort: 8080
      protocol: TCP
{{- end }}
