apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
  namespace: cert-manager
  annotations: { argocd.argoproj.io/sync-wave: '-1' }
spec:
  refreshInterval: 24h
  secretStoreRef: { name: azure-kv-homelab, kind: ClusterSecretStore }
  target: { name: cloudflare-dns }
  data:
    - secretKey: api-token
      remoteRef: { key: cloudflare-api-token }
