# Explicitly choose the deployment mode for clarity and to avoid validation errors.
deploymentMode: SingleBinary

loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  limits_config:
    retention_period: 336h # 14d

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: local-path
    size: 32Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi

# ensure *no* scalable targets run alongside SingleBinary.
read: { replicas: 0 }
write: { replicas: 0 }
backend: { replicas: 0 }
distributor: { replicas: 0 }
ingester: { replicas: 0 }
querier: { replicas: 0 }
queryFrontend: { replicas: 0 }
queryScheduler: { replicas: 0 }
compactor: { replicas: 0 }
indexGateway: { replicas: 0 }
bloomCompactor: { replicas: 0 }
bloomGateway: { replicas: 0 }

monitoring:
  selfMonitoring: { enabled: false } # we'll use KPS for metrics

test: { enabled: false }

chunksCache:
  enabled: true
  allocatedMemory: 256 # MB; chart derives ~1.2x this for mem limit (~307Mi)
  resources:
    requests: { cpu: 100m, memory: 300Mi }
    limits: { memory: 300Mi }

resultsCache:
  enabled: true
  allocatedMemory: 128 # MB; mem limit ~154Mi
  resources:
    requests: { cpu: 50m, memory: 160Mi }
    limits: { memory: 160Mi }
