apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-terraform-runner
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '20' }
spec:
  project: apps
  destination: { server: https://kubernetes.default.svc, namespace: gh-runners }
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/gh-runners-terraform/overlays/klab
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ['ServerSideApply=true']
