apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird-dmz
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '25' }
spec:
  project: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: netbird
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/netbird/overlays/klab/dmz
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ['CreateNamespace=true', 'ServerSideApply=true']
