apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runners-common
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-30' }
spec:
  project: apps
  destination: { server: https://kubernetes.default.svc, namespace: argocd }
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: apps/runners-common/overlays/klab
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ['CreateNamespace=true', 'ServerSideApply=true']
