# VLAN 3 pool (trust)
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: vlan3
spec:
  blocks:
    - cidr: 192.168.3.240/32
    - cidr: 192.168.3.241/32

---
# VLAN 4 pool (dmz)
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: vlan4
spec:
  blocks:
    - cidr: 192.168.4.240/32

---
# L2 announce on VLAN 3
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-vlan3
spec:
  loadBalancerIPs: true
  externalIPs: false
  interfaces:
    - "^enp.*\\.3$"
    - "^bond0\\.3$"

---
# L2 announce on VLAN 4
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-vlan4
spec:
  loadBalancerIPs: true
  externalIPs: false
  interfaces:
    - "^enp.*\\.4$"
    - "^bond0\\.4$"
