# VLAN 3 pool (trust)
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: vlan3
spec:
  cidrs:
    - cidr: 192.168.3.240/32

---
# VLAN 4 pool (dmz)
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: vlan4
spec:
  cidrs:
    - cidr: 192.168.4.240/32

---
# Announce LB IPs on VLAN 3 interface
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-vlan3
spec:
  interfaces:
    - enp0s31f6.3
  externalIPs: false
  loadBalancerIPs: true

---
# Announce LB IPs on VLAN 4 interface
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-vlan4
spec:
  interfaces:
    - enp0s31f6.4
  externalIPs: false
  loadBalancerIPs: true
