runnerScaleSetName: 'arc-ansible'

template:
  spec:
    containers:
      - name: runner
        image: docker.io/gr10/gh-ansible-runner:2.0.0
        env:
          - name: REPO_URL
            valueFrom:
              configMapKeyRef:
                name: gh-runners-config
                key: REPO_URL
          - name: GH_PAT
            valueFrom:
              secretKeyRef:
                name: gh-runners-env
                key: GH_PAT
