runnerScaleSetName: 'arc-docker'

template:
  spec:
    containers:
      - name: runner
        image: docker.io/gr10/gh-docker-runner:2.0.0
        command: ['/home/runner/run.sh'] # explicit, per docs
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: 'false' # temporary to find root cause of issue
          - name: REPO_URL
            valueFrom:
              configMapKeyRef:
                name: gh-runners-config
                key: REPO_URL
          - name: GH_PAT
            valueFrom:
              secretKeyRef:
                name: gh-runners-env
                key: GH_PAT
          - name: BUILDKIT_HOST
            value: 'tcp://buildkitd.gh-runners.svc.cluster.local:1234'
          - name: DOCKER_BUILDKIT
            value: '1'
