runnerScaleSetName: 'arc-docker'

containerMode:
  type: 'kubernetes'
  kubernetesModeWorkVolumeClaim:
    accessModes: ['ReadWriteOnce']
    storageClassName: 'local-path'
    resources: { requests: { storage: '1Gi' } }

template:
  spec:
    containers:
      - name: runner
        image: docker.io/gr10/gh-docker-runner:2.0.0
        env:
          - name: REPO_URL
            valueFrom:
              configMapKeyRef:
                name: gh-runners-config
                key: REPO_URL
          - name: GH_PAT
            valueFrom:
              secretKeyRef:
                name: gh-runners-env
                key: GH_PAT
          - name: BUILDKIT_HOST
            value: 'tcp://buildkitd.gh-runners.svc.cluster.local:1234'
          - name: DOCKER_BUILDKIT
            value: '1'
