apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildkitd
  namespace: agents-and-runners
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: agents-and-runners
  labels: { app: buildkitd }
spec:
  replicas: 1
  selector:
    matchLabels: { app: buildkitd }
  template:
    metadata:
      labels: { app: buildkitd }
    spec:
      serviceAccountName: buildkitd
      securityContext:
        fsGroup: 0
      containers:
        - name: buildkitd
          image: moby/buildkit:v0.23.1
          args:
            - --addr
            - tcp://0.0.0.0:1234
            # Allow entitlements you already used with the k8s driver
            - --allow-insecure-entitlement=security.insecure
            - --allow-insecure-entitlement=network.host
            - --config
            - /etc/buildkit/buildkitd.toml
          ports:
            - name: grpc
              containerPort: 1234
          volumeMounts:
            - name: cfg
              mountPath: /etc/buildkit
              readOnly: true
          resources:
            # Start modest; HPA will add pods when busy
            requests:
              cpu: '1500m'
              memory: '4Gi'
              ephemeral-storage: '8Gi'
            limits:
              cpu: '3'
              memory: '8Gi'
              ephemeral-storage: '32Gi'
          livenessProbe:
            tcpSocket: { port: grpc }
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            tcpSocket: { port: grpc }
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            tcpSocket: { port: grpc }
            failureThreshold: 30
            periodSeconds: 2
          securityContext:
            privileged: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels: { app: buildkitd }
      volumes:
        - name: cfg
          configMap:
            name: buildkitd-config
