apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: buildkitd
  namespace: agents-and-runners
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: buildkitd
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
