resources:
  - namespace.yaml
  - secretstore.yaml
  - externalsecret-gh.yaml
  - externalsecret-tfc.yaml
  - deployment-gh-ansible.yaml
  - deployment-gh-docker.yaml
  - deployment-gh-packer.yaml
  - deployment-gh-terraform.yaml
  - deployment-tfc-agent.yaml
