apiVersion: v1
kind: ServiceAccount
metadata:
  name: gh-buildx
  namespace: agents-and-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildx-controller
  namespace: agents-and-runners
rules:
  # Buildx (driver=kubernetes) creates/controls pods & services and stores state in secrets/cm
  - apiGroups: ['']
    resources:
      [
        'pods',
        'pods/log',
        'services',
        'secrets',
        'configmaps',
        'events',
        'persistentvolumeclaims',
      ]
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch', 'delete']
  - apiGroups: ['apps']
    resources: ['deployments', 'statefulsets', 'replicasets']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch', 'delete']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch', 'delete']
  - apiGroups: ['coordination.k8s.io']
    resources: ['leases']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch', 'delete']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildx-controller
  namespace: agents-and-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildx-controller
subjects:
  - kind: ServiceAccount
    name: gh-buildx
    namespace: agents-and-runners
