apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildx
  namespace: agents-and-runners
---
# Permissions for Buildx (Kubernetes driver + rootful BuildKit)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildx-manager
  namespace: agents-and-runners
rules:
  - apiGroups: ['apps']
    resources: ['deployments', 'replicasets']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']

  - apiGroups: ['']
    resources:
      - pods
      - pods/log
      - pods/exec # <— needed to exec into buildkitd pod
      - pods/attach # optional but common
      - pods/portforward # optional but common
      - services
      - configmaps
      - secrets
      - events
    # exec/attach/portforward need "create"; others use the full set
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']

  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
---
# Bind to all SAs in the namespace (matches your current setup)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildx-manager-to-namespace-sas
  namespace: agents-and-runners
subjects:
  - kind: ServiceAccount
    name: buildx
    namespace: agents-and-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildx-manager
