apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-homelab
spec:
  provider:
    azurekv:
      vaultUrl: https://<YOUR-VAULT-NAME>.vault.azure.net
      authType: ServicePrincipal
      tenantId: <YOUR-AAD-TENANT-ID>
      clientId: <ADD-SP-CLIENT-ID-AS-K8S-SECRET>
      clientSecret:
        name: azure-kv-creds
        key: client-secret
        namespace: agents-and-runners
