apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-homelab
spec:
  provider:
    azurekv:
      vaultUrl: https://kv-homelab-uks.vault.azure.net
      authType: ServicePrincipal
      tenantId: a97d5792-e295-4539-9bf2-7260e2a90ad4
      clientId: 45818531-6511-4241-83a5-636240f15c5b # eso_client_id
      clientSecret:
        name: azure-kv-creds
        key: client-secret
        namespace: external-secrets
