apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-homelab
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
spec:
  provider:
    azurekv:
      vaultUrl: https://kv-homelab-uks.vault.azure.net
      authType: ServicePrincipal
      auth:
        secretRef:
          clientId:
            name: azure-kv-creds
            key: client-id
            namespace: external-secrets
          clientSecret:
            name: azure-kv-creds
            key: client-secret
            namespace: external-secrets
          tenantId:
            name: azure-kv-creds
            key: tenant-id
            namespace: external-secrets
