name: Fetch Azure Key Vault Secrets
description: Log into Azure and fetch a list of secrets from Key Vault

inputs:
  keyvault:
    description: 'Azure Key Vault name'
    required: true
  secrets:
    description: 'Comma-separated list of secret names'
    required: true
  azure_client_id:
    description: 'Azure AD application (client) ID'
    required: true
  azure_tenant_id:
    description: 'Azure AD tenant ID'
    required: true
  azure_subscription_id:
    description: 'Azure subscription ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    - name: Fetch secrets
      shell: bash
      run: |
        IFS=',' read -ra secret_list <<< "${{ inputs.secrets }}"
        for name in "${secret_list[@]}"; do
          val=$(az keyvault secret show \
            --vault-name "${{ inputs.keyvault }}" \
            --name "$name" \
            --query value -o tsv)

          echo "::add-mask::$val"

          key=$(echo "$name" | tr '[:lower:]-' '[:upper:]_')
          printf '%s<<EOF\n%s\nEOF\n' "$key" "$val" >> "$GITHUB_ENV"
        done
