cluster_name         = "homelab"
cluster_endpoint     = "https://k8s-01:6443"
bootstrap_node       = "k8s-01"
install_disk         = "/dev/sda"
storage_account_name = "sthomelabuks"
container_name       = "k8s"
