apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vip-pbr
  namespace: kube-system
  labels: { app: vip-pbr }
spec:
  selector:
    matchLabels: { app: vip-pbr }
  template:
    metadata:
      labels: { app: vip-pbr }
    spec:
      hostNetwork: true
      tolerations:
        - key: 'node-role.kubernetes.io/control-plane'
          operator: 'Exists'
          effect: 'NoSchedule'
      containers:
        - name: pbr
          image: nicolaka/netshoot:latest
          securityContext: { privileged: true } # needs CAP_NET_ADMIN
          command: ['/bin/sh', '-c']
          args:
            - |
              set -eu

              # Table 200 -> VLAN 2 (VIP 192.168.2.240)
              ip -4 route replace 192.168.2.0/24 dev enp0s31f6    scope link table 200
              ip -4 route replace default via 192.168.2.1 dev enp0s31f6           table 200
              ip -4 rule  del     from 192.168.2.240/32 table 200 2>/dev/null || true
              ip -4 rule  add pref 200 from 192.168.2.240/32 lookup 200

              # Table 201 -> VLAN 3 (VIP 192.168.3.240)
              ip -4 route replace 192.168.3.0/24 dev enp0s31f6.3  scope link table 201
              ip -4 route replace default via 192.168.3.1 dev enp0s31f6.3         table 201
              ip -4 rule  del     from 192.168.3.240/32 table 201 2>/dev/null || true
              ip -4 rule  add pref 201 from 192.168.3.240/32 lookup 201

              # Table 202 -> VLAN 4 (VIP 192.168.4.240)
              ip -4 route replace 192.168.4.0/24 dev enp0s31f6.4  scope link table 202
              ip -4 route replace default via 192.168.4.1 dev enp0s31f6.4         table 202
              ip -4 rule  del     from 192.168.4.240/32 table 202 2>/dev/null || true
              ip -4 rule  add pref 202 from 192.168.4.240/32 lookup 202

              # stay alive for kubectl logs
              sleep infinity
