apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vip-pbr
  namespace: kube-system
  labels: { app: vip-pbr }
spec:
  selector:
    matchLabels: { app: vip-pbr }
  template:
    metadata:
      labels: { app: vip-pbr }
    spec:
      hostNetwork: true
      tolerations:
        - key: 'node-role.kubernetes.io/control-plane'
          operator: 'Exists'
          effect: 'NoSchedule'
      containers:
        - name: pbr
          image: nicolaka/netshoot:latest
          securityContext: { privileged: true } # needs CAP_NET_ADMIN
          command: ['/bin/sh', '-c']
          args:
            - |
              set -u

              # ===== VLAN 2 VIP =====
              ip -4 route replace 192.168.2.0/24 dev enp0s31f6    scope link table 102
              ip -4 route replace default via 192.168.2.1 dev enp0s31f6           table 102
              ip -4 rule  del     from 192.168.2.240/32 table 102 2>/dev/null || true
              ip -4 rule  add pref 102 from 192.168.2.240/32 lookup 102

              # ===== VLAN 3 =====
              ip -4 route replace 192.168.3.0/24 dev enp0s31f6.3  scope link table 103
              ip -4 route replace default via 192.168.3.1 dev enp0s31f6.3         table 103
              ip -4 rule  del     from 192.168.3.0/24 table 103 2>/dev/null || true
              ip -4 rule  add pref 103 from 192.168.3.0/24 lookup 103

              # ===== VLAN 4 =====
              ip -4 route replace 192.168.4.0/24 dev enp0s31f6.4  scope link table 104
              ip -4 route replace default via 192.168.4.1 dev enp0s31f6.4         table 104
              ip -4 rule  del     from 192.168.4.0/24 table 104 2>/dev/null || true
              ip -4 rule  add pref 104 from 192.168.4.0/24 lookup 104

              # ===== VLAN 5 =====
              ip -4 route replace 192.168.5.0/24 dev enp0s31f6.5  scope link table 105
              ip -4 route replace default via 192.168.5.1 dev enp0s31f6.5         table 105
              ip -4 rule  del     from 192.168.5.0/24 table 105 2>/dev/null || true
              ip -4 rule  add pref 105 from 192.168.5.0/24 lookup 105

              # ===== VLAN 6 =====
              ip -4 route replace 192.168.6.0/24 dev enp0s31f6.6  scope link table 106
              ip -4 route replace default via 192.168.6.1 dev enp0s31f6.6         table 106
              ip -4 rule  del     from 192.168.6.0/24 table 106 2>/dev/null || true
              ip -4 rule  add pref 106 from 192.168.6.0/24 lookup 106

              exec tail -f /dev/null
