apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ['monitoring']
  selector:
    matchLabels:
      app: alloy
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
