apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: net
resources:
  - ../../../base
  - externalsecret.yaml
patches:
  - target:
      kind: Deployment
      name: netbird
    patch: |-
      - op: replace
        path: /metadata/name
        value: netbird-fam
      - op: replace
        path: /spec/template/metadata/labels/egress.zone
        value: fam
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
        value: netbird-setup-fam
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: netbird-fam
