apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring
spec:
  selector:
    matchLabels: { app: alloy }
  template:
    metadata:
      labels: { app: alloy }
    spec:
      serviceAccountName: alloy
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: alloy
          image: grafana/alloy:v1.10.1
          args:
            [
              'run',
              '/etc/alloy/config.river',
              '--server.http.listen-addr=0.0.0.0:12345',
            ]
          ports:
            - name: http
              containerPort: 12345
          volumeMounts:
            - { name: varlog, mountPath: /var/log }
            - { name: varlib, mountPath: /var/lib }
            - { name: pods, mountPath: /var/log/pods }
            - { name: config, mountPath: /etc/alloy }
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits: { cpu: 500m, memory: 512Mi }
      volumes:
        - name: varlog
          hostPath: { path: /var/log }
        - name: varlib
          hostPath: { path: /var/lib }
        - name: pods
          hostPath: { path: /var/log/pods }
        - name: config
          configMap:
            name: alloy-config
            items: [{ key: config.river, path: config.river }]
      dnsPolicy: ClusterFirst
      hostNetwork: false
  updateStrategy: { type: RollingUpdate }
