---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: observability

---
# Minimal, standard permissions for k8s discovery + pod metadata
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy
rules:
  - apiGroups: ['']
    resources: ['pods', 'namespaces', 'nodes', 'endpoints']
    verbs: ['get', 'list', 'watch']

---
# Bind the SA (in observability) to the ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy
subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: observability
