apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-dmz-tls
  namespace: monitoring
spec:
  secretName: grafana-dmz-tls
  dnsNames: ['grafana.dmz.k8s.internal']
  issuerRef: { kind: ClusterIssuer, name: homelab-ca }
