name: 'Ansible | Scheduled Daily Updates'

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply-updates:
    name: Apply Daily Updates
    runs-on: [self-hosted, ansible]
    defaults:
      run:
        working-directory: ./ansible

    steps:
      - name: Checkout (ansible + local action)
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          sparse-checkout: |
            ansible
            .github/actions/fetch-akv-secrets

      - name: Load secrets from Azure Key Vault
        uses: ./.github/actions/fetch-akv-secrets
        with:
          keyvault: kv-homelab-uks
          secrets: ansible-ssh-private-key,ansible-proxmox-api-user,ansible-proxmox-api-token-id,ansible-proxmox-api-token-secret
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Install Python libs for Proxmox modules
        run: |
          python3 -m pip install --break-system-packages --upgrade pip
          python3 -m pip install --break-system-packages proxmoxer requests

      - name: Set up Ansible SSH key
        env:
          ANSIBLE_SSH_KEY: ${{ env.ANSIBLE_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$ANSIBLE_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run the state-aware update playbook
        env:
          PROXMOX_URL: 'https://pve02.internal:8006/api2/json' # inventory plugin
          PROXMOX_HOST: 'pve02.internal:8006' # modules
          PROXMOX_USER: ${{ env.ANSIBLE_PROXMOX_API_USER }}
          PROXMOX_TOKEN_ID: ${{ env.ANSIBLE_PROXMOX_API_TOKEN_ID }}
          PROXMOX_TOKEN_SECRET: ${{ env.ANSIBLE_PROXMOX_API_TOKEN_SECRET }}
        run: ansible-playbook playbook.updates.yml -v
