---
# Switch the guest off only if _pc_started_by_playbook is set.

- name: Choose VMID and node variables
  ansible.builtin.set_fact:
    _pc_vmid: '{{ vmid | default(proxmox_vmid, true) }}'
    _pc_node: '{{ node | default(proxmox_node, true) }}'
    _pc_api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
    _pc_api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
    _pc_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
    _pc_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"

- name: Stop QEMU VM we powered on
  delegate_to: localhost
  community.proxmox.proxmox_kvm:
    api_host: '{{ _pc_api_host }}'
    api_user: '{{ _pc_api_user }}'
    api_token_id: '{{ _pc_token_id }}'
    api_token_secret: '{{ _pc_token_secret }}'
    vmid: '{{ _pc_vmid }}'
    node: '{{ _pc_node }}'
    state: stopped
  when:
    - _pc_started_by_playbook | default(false)
    - proxmox_vmtype | default('qemu') == 'qemu'

- name: Stop LXC container we powered on
  delegate_to: localhost
  community.proxmox.proxmox:
    api_host: '{{ _pc_api_host }}'
    api_user: '{{ _pc_api_user }}'
    api_token_id: '{{ _pc_token_id }}'
    api_token_secret: '{{ _pc_token_secret }}'
    vmid: '{{ _pc_vmid }}'
    node: '{{ _pc_node }}'
    state: stopped
  when:
    - _pc_started_by_playbook | default(false)
    - proxmox_vmtype | default('lxc') == 'lxc'
